/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CLAVES_H_RPCGEN
#define _CLAVES_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct args {
	int key;
	char *value1;
	int N_value2;
	double V_value2[32];
};
typedef struct args args;

struct get_value_result {
	char *value1;
	int N_value2;
	double V_value2[32];
	int status;
};
typedef struct get_value_result get_value_result;

#define CLAVES 99
#define CLAVESVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define rpc_init 1
extern  enum clnt_stat rpc_init_1(int *, CLIENT *);
extern  bool_t rpc_init_1_svc(int *, struct svc_req *);
#define rpc_set_value 2
extern  enum clnt_stat rpc_set_value_1(struct args , int *, CLIENT *);
extern  bool_t rpc_set_value_1_svc(struct args , int *, struct svc_req *);
#define rpc_get_value 3
extern  enum clnt_stat rpc_get_value_1(int , get_value_result *, CLIENT *);
extern  bool_t rpc_get_value_1_svc(int , get_value_result *, struct svc_req *);
#define rpc_modify_value 4
extern  enum clnt_stat rpc_modify_value_1(struct args , int *, CLIENT *);
extern  bool_t rpc_modify_value_1_svc(struct args , int *, struct svc_req *);
#define rpc_delete_key 5
extern  enum clnt_stat rpc_delete_key_1(int , int *, CLIENT *);
extern  bool_t rpc_delete_key_1_svc(int , int *, struct svc_req *);
#define rpc_exist 6
extern  enum clnt_stat rpc_exist_1(int , int *, CLIENT *);
extern  bool_t rpc_exist_1_svc(int , int *, struct svc_req *);
extern int claves_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define rpc_init 1
extern  enum clnt_stat rpc_init_1();
extern  bool_t rpc_init_1_svc();
#define rpc_set_value 2
extern  enum clnt_stat rpc_set_value_1();
extern  bool_t rpc_set_value_1_svc();
#define rpc_get_value 3
extern  enum clnt_stat rpc_get_value_1();
extern  bool_t rpc_get_value_1_svc();
#define rpc_modify_value 4
extern  enum clnt_stat rpc_modify_value_1();
extern  bool_t rpc_modify_value_1_svc();
#define rpc_delete_key 5
extern  enum clnt_stat rpc_delete_key_1();
extern  bool_t rpc_delete_key_1_svc();
#define rpc_exist 6
extern  enum clnt_stat rpc_exist_1();
extern  bool_t rpc_exist_1_svc();
extern int claves_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_args (XDR *, args*);
extern  bool_t xdr_get_value_result (XDR *, get_value_result*);

#else /* K&R C */
extern bool_t xdr_args ();
extern bool_t xdr_get_value_result ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CLAVES_H_RPCGEN */
