
# This is a template Makefile generated by rpcgen

# Parameters

CLIENT = cliente_tests cliente_concurrente
SERVER = servidor

SOURCES_CLNT.c = 
SOURCES_CLNT.h = 
SOURCES_SVC.c = 
SOURCES_SVC.h = 
SOURCES.x = claves.x

TARGETS_SVC.c = claves_svc.c servidor.c claves_xdr.c funciones_servidor/funciones_servidor.c
TARGETS_CLNT.c = claves_clnt.c claves/claves.c claves_xdr.c 
TARGETS = claves.h claves_xdr.c claves_clnt.c claves_svc.c

OBJECTS_CLNT = $(SOURCES_CLNT.c:%.c=%.o) $(TARGETS_CLNT.c:%.c=%.o)
OBJECTS_SVC = $(SOURCES_SVC.c:%.c=%.o) $(TARGETS_SVC.c:%.c=%.o)
# Compiler flags 

CPPFLAGS += -D_REENTRANT
CFLAGS += -g -I/usr/include/tirpc -fPIC
LDLIBS += -lnsl -lpthread -lrt -ltirpc
RPCGENFLAGS = -NMa

# Targets 

all : libclaves.so $(CLIENT) $(SERVER)

%.o: %.c
	@echo "Compiling... $<"
	$(CC) $(CFLAGS) -c $< -o $@

libclaves.so: $(OBJECTS_CLNT)
	$(CC) $(LDFLAGS) -shared -o $@ $(OBJECTS_CLNT) $(LDLIBS)

$(TARGETS) : $(SOURCES.x) 
	rpcgen $(RPCGENFLAGS) $(SOURCES.x)

$(OBJECTS_CLNT) : $(SOURCES_CLNT.c) $(SOURCES_CLNT.h) $(TARGETS_CLNT.c) 

$(OBJECTS_SVC) : $(SOURCES_SVC.c) $(SOURCES_SVC.h) $(TARGETS_SVC.c) 

$(CLIENT) : cliente_tests.o cliente_concurrente.o
	$(CC) -o cliente_tests cliente_tests.o $(LDLIBS) -L. -lclaves
	$(CC) -o cliente_concurrente cliente_concurrente.o $(LDLIBS) -L. -lclaves

$(SERVER) : $(OBJECTS_SVC) 
	$(CC) -o $(SERVER) $(OBJECTS_SVC) $(LDLIBS)

 clean:
	 $(RM) core $(OBJECTS_CLNT) $(OBJECTS_SVC) $(CLIENT) $(SERVER) libclaves.so claves_client cliente_concurrente.o cliente_tests.o tuplas.txt

